export const tableLookup = [
  //times of the day is the first arr
  [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
  ],
  [
    //first element =
    { day: "Monday", disabled: true },
    { day: "Monday", time: "12:00am" },
    { day: "Monday", time: "12:30am" },
    { day: "Monday", time: "01:00am" },
    { day: "Monday", time: "01:30am" },
    { day: "Monday", time: "02:00am" },
    { day: "Monday", time: "02:30am" },
    { day: "Monday", time: "03:00am" },
    { day: "Monday", time: "03:30am" },
    { day: "Monday", time: "04:00am" },
    { day: "Monday", time: "04:30am" },
    { day: "Monday", time: "05:00am" },
    { day: "Monday", time: "05:30am" },
    { day: "Monday", time: "06:00am" },
    { day: "Monday", time: "06:30am" },
    { day: "Monday", time: "07:00am" },
    { day: "Monday", time: "07:30am" },
    { day: "Monday", time: "08:00am" },
    { day: "Monday", time: "08:30am" },
    { day: "Monday", time: "09:00am" },
    { day: "Monday", time: "09:30am" },
    { day: "Monday", time: "10:00am" },
    { day: "Monday", time: "10:30am" },
    { day: "Monday", time: "11:00pm" },
    { day: "Monday", time: "11:30pm" },
    { day: "Monday", time: "12:00pm" },
    { day: "Monday", time: "12:30pm" },
    { day: "Monday", time: "01:00pm" },
    { day: "Monday", time: "01:30pm" },
    { day: "Monday", time: "02:00pm" },
    { day: "Monday", time: "02:30pm" },
    { day: "Monday", time: "03:00pm" },
    { day: "Monday", time: "03:30pm" },
    { day: "Monday", time: "04:00pm" },
    { day: "Monday", time: "04:30pm" },
    { day: "Monday", time: "05:00pm" },
    { day: "Monday", time: "05:30pm" },
    { day: "Monday", time: "06:00pm" },
    { day: "Monday", time: "06:30pm" },
    { day: "Monday", time: "07:00pm" },
    { day: "Monday", time: "07:30pm" },
    { day: "Monday", time: "08:00pm" },
    { day: "Monday", time: "08:30pm" },
    { day: "Monday", time: "09:00pm" },
    { day: "Monday", time: "09:30pm" },
    { day: "Monday", time: "10:00pm" },
    { day: "Monday", time: "10:30pm" },
    { day: "Monday", time: "11:00pm" },
    { day: "Monday", time: "11:30pm" },
    { day: "Monday", time: "11:59pm" },
  ],
  [
    { day: "Tuesday", disabled: true },
    { day: "Tuesday", time: "12:00am" },
    { day: "Tuesday", time: "12:30am" },
    { day: "Tuesday", time: "01:00am" },
    { day: "Tuesday", time: "01:30am" },
    { day: "Tuesday", time: "02:00am" },
    { day: "Tuesday", time: "02:30am" },
    { day: "Tuesday", time: "03:00am" },
    { day: "Tuesday", time: "03:30am" },
    { day: "Tuesday", time: "04:00am" },
    { day: "Tuesday", time: "04:30am" },
    { day: "Tuesday", time: "05:00am" },
    { day: "Tuesday", time: "05:30am" },
    { day: "Tuesday", time: "06:00am" },
    { day: "Tuesday", time: "06:30am" },
    { day: "Tuesday", time: "07:00am" },
    { day: "Tuesday", time: "07:30am" },
    { day: "Tuesday", time: "08:00am" },
    { day: "Tuesday", time: "08:30am" },
    { day: "Tuesday", time: "09:00am" },
    { day: "Tuesday", time: "09:30am" },
    { day: "Tuesday", time: "10:00am" },
    { day: "Tuesday", time: "10:30am" },
    { day: "Tuesday", time: "11:00pm" },
    { day: "Tuesday", time: "11:30pm" },
    { day: "Tuesday", time: "12:00pm" },
    { day: "Tuesday", time: "12:30pm" },
    { day: "Tuesday", time: "01:00pm" },
    { day: "Tuesday", time: "01:30pm" },
    { day: "Tuesday", time: "02:00pm" },
    { day: "Tuesday", time: "02:30pm" },
    { day: "Tuesday", time: "03:00pm" },
    { day: "Tuesday", time: "03:30pm" },
    { day: "Tuesday", time: "04:00pm" },
    { day: "Tuesday", time: "04:30pm" },
    { day: "Tuesday", time: "05:00pm" },
    { day: "Tuesday", time: "05:30pm" },
    { day: "Tuesday", time: "06:00pm" },
    { day: "Tuesday", time: "06:30pm" },
    { day: "Tuesday", time: "07:00pm" },
    { day: "Tuesday", time: "07:30pm" },
    { day: "Tuesday", time: "08:00pm" },
    { day: "Tuesday", time: "08:30pm" },
    { day: "Tuesday", time: "09:00pm" },
    { day: "Tuesday", time: "09:30pm" },
    { day: "Tuesday", time: "10:00pm" },
    { day: "Tuesday", time: "10:30pm" },
    { day: "Tuesday", time: "11:00pm" },
    { day: "Tuesday", time: "11:30pm" },
    { day: "Tuesday", time: "11:59pm" },
  ],
  [
    { day: "Wednesday", disabled: true },
    { day: "Wednesday", time: "12:00am" },
    { day: "Wednesday", time: "12:30am" },
    { day: "Wednesday", time: "01:00am" },
    { day: "Wednesday", time: "01:30am" },
    { day: "Wednesday", time: "02:00am" },
    { day: "Wednesday", time: "02:30am" },
    { day: "Wednesday", time: "03:00am" },
    { day: "Wednesday", time: "03:30am" },
    { day: "Wednesday", time: "04:00am" },
    { day: "Wednesday", time: "04:30am" },
    { day: "Wednesday", time: "05:00am" },
    { day: "Wednesday", time: "05:30am" },
    { day: "Wednesday", time: "06:00am" },
    { day: "Wednesday", time: "06:30am" },
    { day: "Wednesday", time: "07:00am" },
    { day: "Wednesday", time: "07:30am" },
    { day: "Wednesday", time: "08:00am" },
    { day: "Wednesday", time: "08:30am" },
    { day: "Wednesday", time: "09:00am" },
    { day: "Wednesday", time: "09:30am" },
    { day: "Wednesday", time: "10:00am" },
    { day: "Wednesday", time: "10:30am" },
    { day: "Wednesday", time: "11:00pm" },
    { day: "Wednesday", time: "11:30pm" },
    { day: "Wednesday", time: "12:00pm" },
    { day: "Wednesday", time: "12:30pm" },
    { day: "Wednesday", time: "01:00pm" },
    { day: "Wednesday", time: "01:30pm" },
    { day: "Wednesday", time: "02:00pm" },
    { day: "Wednesday", time: "02:30pm" },
    { day: "Wednesday", time: "03:00pm" },
    { day: "Wednesday", time: "03:30pm" },
    { day: "Wednesday", time: "04:00pm" },
    { day: "Wednesday", time: "04:30pm" },
    { day: "Wednesday", time: "05:00pm" },
    { day: "Wednesday", time: "05:30pm" },
    { day: "Wednesday", time: "06:00pm" },
    { day: "Wednesday", time: "06:30pm" },
    { day: "Wednesday", time: "07:00pm" },
    { day: "Wednesday", time: "07:30pm" },
    { day: "Wednesday", time: "08:00pm" },
    { day: "Wednesday", time: "08:30pm" },
    { day: "Wednesday", time: "09:00pm" },
    { day: "Wednesday", time: "09:30pm" },
    { day: "Wednesday", time: "10:00pm" },
    { day: "Wednesday", time: "10:30pm" },
    { day: "Wednesday", time: "11:00pm" },
    { day: "Wednesday", time: "11:30pm" },
    { day: "Wednesday", time: "11:59pm" },
  ],
  [
    { day: "Thursday", disabled: true },
    { day: "Thursday", time: "12:00am" },
    { day: "Thursday", time: "12:30am" },
    { day: "Thursday", time: "01:00am" },
    { day: "Thursday", time: "01:30am" },
    { day: "Thursday", time: "02:00am" },
    { day: "Thursday", time: "02:30am" },
    { day: "Thursday", time: "03:00am" },
    { day: "Thursday", time: "03:30am" },
    { day: "Thursday", time: "04:00am" },
    { day: "Thursday", time: "04:30am" },
    { day: "Thursday", time: "05:00am" },
    { day: "Thursday", time: "05:30am" },
    { day: "Thursday", time: "06:00am" },
    { day: "Thursday", time: "06:30am" },
    { day: "Thursday", time: "07:00am" },
    { day: "Thursday", time: "07:30am" },
    { day: "Thursday", time: "08:00am" },
    { day: "Thursday", time: "08:30am" },
    { day: "Thursday", time: "09:00am" },
    { day: "Thursday", time: "09:30am" },
    { day: "Thursday", time: "10:00am" },
    { day: "Thursday", time: "10:30am" },
    { day: "Thursday", time: "11:00pm" },
    { day: "Thursday", time: "11:30pm" },
    { day: "Thursday", time: "12:00pm" },
    { day: "Thursday", time: "12:30pm" },
    { day: "Thursday", time: "01:00pm" },
    { day: "Thursday", time: "01:30pm" },
    { day: "Thursday", time: "02:00pm" },
    { day: "Thursday", time: "02:30pm" },
    { day: "Thursday", time: "03:00pm" },
    { day: "Thursday", time: "03:30pm" },
    { day: "Thursday", time: "04:00pm" },
    { day: "Thursday", time: "04:30pm" },
    { day: "Thursday", time: "05:00pm" },
    { day: "Thursday", time: "05:30pm" },
    { day: "Thursday", time: "06:00pm" },
    { day: "Thursday", time: "06:30pm" },
    { day: "Thursday", time: "07:00pm" },
    { day: "Thursday", time: "07:30pm" },
    { day: "Thursday", time: "08:00pm" },
    { day: "Thursday", time: "08:30pm" },
    { day: "Thursday", time: "09:00pm" },
    { day: "Thursday", time: "09:30pm" },
    { day: "Thursday", time: "10:00pm" },
    { day: "Thursday", time: "10:30pm" },
    { day: "Thursday", time: "11:00pm" },
    { day: "Thursday", time: "11:30pm" },
    { day: "Thursday", time: "11:59pm" },
  ],
  [
    { day: "Friday", disabled: true },
    { day: "Friday", time: "12:00am" },
    { day: "Friday", time: "12:30am" },
    { day: "Friday", time: "01:00am" },
    { day: "Friday", time: "01:30am" },
    { day: "Friday", time: "02:00am" },
    { day: "Friday", time: "02:30am" },
    { day: "Friday", time: "03:00am" },
    { day: "Friday", time: "03:30am" },
    { day: "Friday", time: "04:00am" },
    { day: "Friday", time: "04:30am" },
    { day: "Friday", time: "05:00am" },
    { day: "Friday", time: "05:30am" },
    { day: "Friday", time: "06:00am" },
    { day: "Friday", time: "06:30am" },
    { day: "Friday", time: "07:00am" },
    { day: "Friday", time: "07:30am" },
    { day: "Friday", time: "08:00am" },
    { day: "Friday", time: "08:30am" },
    { day: "Friday", time: "09:00am" },
    { day: "Friday", time: "09:30am" },
    { day: "Friday", time: "10:00am" },
    { day: "Friday", time: "10:30am" },
    { day: "Friday", time: "11:00pm" },
    { day: "Friday", time: "11:30pm" },
    { day: "Friday", time: "12:00pm" },
    { day: "Friday", time: "12:30pm" },
    { day: "Friday", time: "01:00pm" },
    { day: "Friday", time: "01:30pm" },
    { day: "Friday", time: "02:00pm" },
    { day: "Friday", time: "02:30pm" },
    { day: "Friday", time: "03:00pm" },
    { day: "Friday", time: "03:30pm" },
    { day: "Friday", time: "04:00pm" },
    { day: "Friday", time: "04:30pm" },
    { day: "Friday", time: "05:00pm" },
    { day: "Friday", time: "05:30pm" },
    { day: "Friday", time: "06:00pm" },
    { day: "Friday", time: "06:30pm" },
    { day: "Friday", time: "07:00pm" },
    { day: "Friday", time: "07:30pm" },
    { day: "Friday", time: "08:00pm" },
    { day: "Friday", time: "08:30pm" },
    { day: "Friday", time: "09:00pm" },
    { day: "Friday", time: "09:30pm" },
    { day: "Friday", time: "10:00pm" },
    { day: "Friday", time: "10:30pm" },
    { day: "Friday", time: "11:00pm" },
    { day: "Friday", time: "11:30pm" },
    { day: "Friday", time: "11:59pm" },
  ],
  [
    { day: "Saturday", disabled: true },
    { day: "Saturday", time: "12:00am" },
    { day: "Saturday", time: "12:30am" },
    { day: "Saturday", time: "01:00am" },
    { day: "Saturday", time: "01:30am" },
    { day: "Saturday", time: "02:00am" },
    { day: "Saturday", time: "02:30am" },
    { day: "Saturday", time: "03:00am" },
    { day: "Saturday", time: "03:30am" },
    { day: "Saturday", time: "04:00am" },
    { day: "Saturday", time: "04:30am" },
    { day: "Saturday", time: "05:00am" },
    { day: "Saturday", time: "05:30am" },
    { day: "Saturday", time: "06:00am" },
    { day: "Saturday", time: "06:30am" },
    { day: "Saturday", time: "07:00am" },
    { day: "Saturday", time: "07:30am" },
    { day: "Saturday", time: "08:00am" },
    { day: "Saturday", time: "08:30am" },
    { day: "Saturday", time: "09:00am" },
    { day: "Saturday", time: "09:30am" },
    { day: "Saturday", time: "10:00am" },
    { day: "Saturday", time: "10:30am" },
    { day: "Saturday", time: "11:00pm" },
    { day: "Saturday", time: "11:30pm" },
    { day: "Saturday", time: "12:00pm" },
    { day: "Saturday", time: "12:30pm" },
    { day: "Saturday", time: "01:00pm" },
    { day: "Saturday", time: "01:30pm" },
    { day: "Saturday", time: "02:00pm" },
    { day: "Saturday", time: "02:30pm" },
    { day: "Saturday", time: "03:00pm" },
    { day: "Saturday", time: "03:30pm" },
    { day: "Saturday", time: "04:00pm" },
    { day: "Saturday", time: "04:30pm" },
    { day: "Saturday", time: "05:00pm" },
    { day: "Saturday", time: "05:30pm" },
    { day: "Saturday", time: "06:00pm" },
    { day: "Saturday", time: "06:30pm" },
    { day: "Saturday", time: "07:00pm" },
    { day: "Saturday", time: "07:30pm" },
    { day: "Saturday", time: "08:00pm" },
    { day: "Saturday", time: "08:30pm" },
    { day: "Saturday", time: "09:00pm" },
    { day: "Saturday", time: "09:30pm" },
    { day: "Saturday", time: "10:00pm" },
    { day: "Saturday", time: "10:30pm" },
    { day: "Saturday", time: "11:00pm" },
    { day: "Saturday", time: "11:30pm" },
    { day: "Saturday", time: "11:59pm" },
  ],

  [
    { day: "Sunday", disabled: true },
    { day: "Sunday", time: "12:00am" },
    { day: "Sunday", time: "12:30am" },
    { day: "Sunday", time: "01:00am" },
    { day: "Sunday", time: "01:30am" },
    { day: "Sunday", time: "02:00am" },
    { day: "Sunday", time: "02:30am" },
    { day: "Sunday", time: "03:00am" },
    { day: "Sunday", time: "03:30am" },
    { day: "Sunday", time: "04:00am" },
    { day: "Sunday", time: "04:30am" },
    { day: "Sunday", time: "05:00am" },
    { day: "Sunday", time: "05:30am" },
    { day: "Sunday", time: "06:00am" },
    { day: "Sunday", time: "06:30am" },
    { day: "Sunday", time: "07:00am" },
    { day: "Sunday", time: "07:30am" },
    { day: "Sunday", time: "08:00am" },
    { day: "Sunday", time: "08:30am" },
    { day: "Sunday", time: "09:00am" },
    { day: "Sunday", time: "09:30am" },
    { day: "Sunday", time: "10:00am" },
    { day: "Sunday", time: "10:30am" },
    { day: "Sunday", time: "11:00pm" },
    { day: "Sunday", time: "11:30pm" },
    { day: "Sunday", time: "12:00pm" },
    { day: "Sunday", time: "12:30pm" },
    { day: "Sunday", time: "01:00pm" },
    { day: "Sunday", time: "01:30pm" },
    { day: "Sunday", time: "02:00pm" },
    { day: "Sunday", time: "02:30pm" },
    { day: "Sunday", time: "03:00pm" },
    { day: "Sunday", time: "03:30pm" },
    { day: "Sunday", time: "04:00pm" },
    { day: "Sunday", time: "04:30pm" },
    { day: "Sunday", time: "05:00pm" },
    { day: "Sunday", time: "05:30pm" },
    { day: "Sunday", time: "06:00pm" },
    { day: "Sunday", time: "06:30pm" },
    { day: "Sunday", time: "07:00pm" },
    { day: "Sunday", time: "07:30pm" },
    { day: "Sunday", time: "08:00pm" },
    { day: "Sunday", time: "08:30pm" },
    { day: "Sunday", time: "09:00pm" },
    { day: "Sunday", time: "09:30pm" },
    { day: "Sunday", time: "10:00pm" },
    { day: "Sunday", time: "10:30pm" },
    { day: "Sunday", time: "11:00pm" },
    { day: "Sunday", time: "11:30pm" },
    { day: "Sunday", time: "11:59pm" },
  ],
];
